version: '3.8'

services:
  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma
    environment:
      - PERSIST_DIRECTORY=/chroma

  app:
    build: .
    depends_on:
      - chroma
    environment:
      - CHROMA_SERVER_HOST=chroma
      - CHROMA_SERVER_PORT=8000
    volumes:
      - .:/app

volumes:
  chroma-data: